name: CI
run-name: CI
on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/*test*.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

env:
  GH_TOKEN: ${{ github.token }}
  SRC_DIR: /home/kxxt/Workspaces/chromium/src
  RELEASE_OUT_DIR: /home/kxxt/Workspaces/chromium/src/out/Release-riscv64
  DEBUG_OUT_DIR: /home/kxxt/Workspaces/chromium/src/out/Debug-riscv64
  CCACHE_SLOPPINESS: time_macros,modules
  CCACHE_DEPEND: true
  CCACHE_DIRECT: true

jobs:
  Sync:
    runs-on: magmar
    steps:
      - name: Sync sources
        run: |
          set -ex
          cd "$SRC_DIR"
          git clean -fd
          git reset --hard
          git fetch --tags
          git checkout main
          git pull
          gclient sync -D --force
          git checkout --detach
      - name: Patch
        run: |
          set -ex
          cd "$SRC_DIR"
          # Sandbox
          git fetch https://chromium.googlesource.com/chromium/src refs/changes/20/4935120/11 && git cherry-pick FETCH_HEAD
          # Swiftshader
          git -C third_party/swiftshader fetch https://swiftshader.googlesource.com/SwiftShader refs/changes/29/75929/2 && git -C third_party/swiftshader cherry-pick FETCH_HEAD
          # V8
          git -C v8 fetch https://chromium.googlesource.com/v8/v8 refs/changes/86/8037086/4 && git -C v8 cherry-pick FETCH_HEAD
          # FFmpeg
          # Base
  Release-Build:
    needs: Sync
    runs-on: magmar
    timeout-minutes: 600
    steps:
      - name: Configure (Release)
        run: |
          set -ex
          cd "$SRC_DIR"
          export PATH="$PWD/buildtools/linux64:$PATH"
          gn gen "$RELEASE_OUT_DIR"  --args='
            cc_wrapper="ccache"
            is_official_build=true
            is_debug=false
            target_cpu="riscv64"
            treat_warnings_as_errors=false
            chrome_pgo_phase=0
            use_debug_fission=false
            symbol_level=1'
      - name: Build (Release)
        run: |
          set -ex
          cd "$SRC_DIR"
          export PATH="$PWD/buildtools/linux64:$PATH"
          autoninja -C "$RELEASE_OUT_DIR" chrome.stripped v8/test/cctest
          # TODO: v8 cctest failed to build in debug mode
          # Move v8 test binaries to clang_x64_v8_riscv64/
          mv "$RELEASE_OUT_DIR"/cctest "$RELEASE_OUT_DIR"/clang_x64_v8_riscv64/
  
  Debug-Build:
    needs: Sync
    runs-on: magmar
    timeout-minutes: 600
    steps:
      - name: Configure (Debug)
        run: |
          set -ex
          cd "$SRC_DIR"
          export PATH="$PWD/buildtools/linux64:$PATH"
          gn gen "$DEBUG_OUT_DIR"  --args='
            cc_wrapper="ccache"
            is_debug=true
            target_cpu="riscv64"
            treat_warnings_as_errors=false
            chrome_pgo_phase=0
            use_debug_fission=false
            symbol_level=2'
      - name: Build (Debug)
        run: |
          set -ex
          cd "$SRC_DIR"
          export PATH="$PWD/buildtools/linux64:$PATH"
          autoninja -C "$DEBUG_OUT_DIR" chrome base_unittests cc_unittests net_unittests

  base_unittests_debug:
    needs: Debug-Build
    uses: ./.github/workflows/base_unittests.yml
    with:
      build-mode: Debug
  cc_unittests_debug:
    needs: Debug-Build
    uses: ./.github/workflows/cc_unittests.yml
    with:
      build-mode: Debug
  net_unittests_debug:
    needs: Debug-Build
    uses: ./.github/workflows/net_unittests.yml
    with:
      build-mode: Debug
  v8_tests_release:
    needs: Release-Build
    uses: ./.github/workflows/v8_tests.yml
    with:
      build-mode: Release
